### PR TITLE
fix(troika-three-text): remove IIFEs for tree-shaking

### LINKED ISSUE #215: Allow `troika-three-text` to work with bundle tree-shaking
Hello, I'm using the `@react-three/drei` library, which includes `troika-three-text` to power its Text component. The problem is, even when not using the Text component, `troika-three-text` currently ends up taking 71.6KB of space (after gzipping) in my production bundle.

I believe the reason this happens is because of the IIFE here:
https://github.com/protectwise/troika/blob/c6a10ae30837d26505d5614b8e15ab49f2ad4625/packages/troika-three-text/src/Text.js#L774

If the initialization logic is moved to the constructor, or is otherwise made lazily invoked, I believe this would fix the issue.

Thanks!

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #215. IIFEs cannot be statically analyzed for tree-shaking -- their scope is forced into the bundle regardless of usage.

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
I can verify this on my end today/tomorrow. This should be released before my other PR so it can be backported.

**Comment by CodyJasonBennett** [comment]
There was indeed a prototype mutation for r109 compat. I've moved it to the class as an overload in b55a0c8ceba3ab2ecc30a07a2a254b6f532a393f. This or similar work-arounds <r125 can be removed following #215.

**Comment by CodyJasonBennett** [comment]
I created a generic testing repo and a branch with a local copy of this PR at https://github.com/CodyJasonBennett/treeshaking/tree/troika. Tree-shaking seems to work everywhere but Parcel which doesn't seem to tree-shake with the given configuration. I tested between Rollup, ESBuild, Vite, Webpack, and Parcel.

**Comment by lojjic** [comment]
@CodyJasonBennett We've got some merge conflicts now, could you please resolve them? I've merged #225 so the workarounds you mentioned can probably be removed too.

**Comment by lojjic** [comment]
Actually there may be some mis-resolved conflicts -- I'm seeing a return from PlaneGeometry to PlaneBufferGeometry in the diff...?

**Comment by CodyJasonBennett** [comment]
Resolved them.

**Comment by lojjic** [comment]
Thank you!

**Comment by lojjic** [comment]
v0.47.0 is published.

**Pull request merged**
